name: Simplespit
version: ${project.version}
main: lv.voop.simplespit.core
api-version: 1.13
authors: [VoopLV, Commissar_Voop]
website: voop.lv
commands:
  spit:
    description: Spit Like A Llama As A Player
